### PR TITLE
Refactor: Moved tensoflow from extra_requires to install_requires 

### PR DESCRIPTION
**Pull request by sanidhyamangal**
Since TensorFlow is the backbone of TF GAN module so the user might fail or forget to install TF explicitly when in production or a new environment. Hence, it will be nice to move TensorFlow back into install_requires from extra_requires

### CODE REVIEW

**Comment by joel-shor** [comment]
Because TF came in different flavors for a while (GPU vs non-GPU), I believe best practices used to be to not include TF by default. TF-GAN explicitly runs a check at import to make sure TF is install, so while its not installed automatically it will fail gracefully. Do you know if this has changed? If not, I think we should keep it as is, no?

**Comment by aaronsarna** [comment]
Based on https://www.tensorflow.org/install/pip tensorflow-gpu is still needed for GPU support for TFv1. In TF2 the standard tensorflow package has GPU support. I think we can't make this switch unless we drop TF1 support.

Also, the style changes made in this PR are not following the Google style guide. Please revert them.

**Comment by aaronsarna** [comment]
Sorry, to clarify, we are following the same conventions as [Tensorflow](https://www.tensorflow.org/community/contribute/code_style) for style, so we follow the Google style guide except for using 2 space indents instead of 4.

**Comment by sanidhyamangal** [comment]
@aaronsarna I completely agree with you, will revert the changes and close the PR for now. Also, as per our conversation, I am interested in the redesign of the framework to support Keras Models and TF2 eager mode in GSoC thus it will be nice, if you could point out some good first changes, to begin with. 

Sorry my bad for styling, failed to read Tensorflow's styling guide. I assumed you are using Yapf formatting.

**Comment by sanidhyamangal** [comment]
@joel-shor, it is working fine with the previous version. So I think it's better not to change it now. Hence, closing the PR.

**Pull request closed without merging**
